version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22.15.0
      
    commands:
      - echo "Installing AWS CLI"
      - npm ci --legacy-peer-deps

  build:
    commands:
      - echo "Syncing files to S3"
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: dist
  discard-paths: no