version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - cd server && npm install
      - cd ../client && npm install
      - cd ..
  
  pre_build:
    commands:
      - echo Running pre-build checks...
      - echo Build started on `date`
      - echo Testing server dependencies...
      - cd server && npm list --depth=0
      - echo Testing client dependencies...
      - cd ../client && npm list --depth=0
      - cd ..
  
  build:
    commands:
      - cd client && npm run build
      - cd ..
      - mkdir -p dist
      - cp -r client/build/* dist/

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'

cache:
  paths:
    - 'server/node_modules/**/*'
    - 'client/node_modules/**/*'